apiVersion: v1
kind: Service
metadata:
  name: qod-api
  labels:
    app: qod-api
    tier: api
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: qod-api
